### ISSUE TITLE
0.19 Upgrade Considerations

### ISSUE THREAD

**Issue by sch** [eskimoblood/elm-color-extra#26]
Hi 👋 

Thanks for all of your work maintaining this package. I wanted to know if you intended to upgrade it for Elm 0.19, which removes the `Color` package entirely.

There's been some talk about breaking the old `Color` package out as a stand-alone package under `elm/color`, but nothing is definitive.

I also wanted to ask if, in light of that fact, you might consider duplicating the `Color` definitions within this package, so that existing applications have a smooth upgrade path.

**Comment by eskimoblood** [comment]
As I'm not so much interested in elm anymore I was not aware of this. How do they handle colors now? If its easy I could at the old package code, but I would also like if someones with more interest in this topic could to this.

**Comment by sch** [comment]
There's an unpublished Color package on [elm/color](https://github.com/elm/color) nowadays. It may be published as-is, or it may undergo some API changes first.

I made a proof-of-concept upgrade in #27 with a bit more info detailing the changes. Let me know your thoughts — based on what's going on in elm/color#1, it may be worth holding off.

**Comment by eskimoblood** [comment]
Yeah, let's wait and see how they decide.

**Comment by absynce** [comment]
It looks like elm/color is moving to [avh4/elm-color](https://github.com/avh4/elm-color).

**Comment by avh4** [comment]
Just published https://package.elm-lang.org/packages/avh4/elm-color/latest/

Also, I'd be interested in thoughts about what, if anything, would make sense to move from elm-color-extra to elm-color.  (Feel free to make a github issue there for any such ideas.)

**Comment by noahzgordon** [comment]
@eskimoblood thank you for all your hard work on this library! since I wanted to use its functionality very badly, I forked it, upgraded it and released it under my namespace. the upgraded library can be found here: https://package.elm-lang.org/packages/noahzgordon/elm-color-extra/latest/

since you are not interested in Elm these days, would you be all right with me continuing as the library's maintainer?

@avh4 I would also be happy to move any of this functionality into your `Color` library! as long as it's all third-party anyway, I think it makes the most sense under one umbrella. let me know what you think.

**Comment by eskimoblood** [comment]
>since you are not interested in Elm these days, would you be all right with me continuing as the library's maintainer?

Sure, go ahead.
